language: java

jdk:
  - openjdk11

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "nePvWR3QROi5tjh39/zlwVvDmKd0NaFHSuvmyfUoL3bNnqe/xP26UYvwhmEBHkkfKdKETGowzCLeA5vH1bQSULtBWcW38ugRNro4jMWx+X9Ocy1MNrd3XmrHl7pGDcRz5jjR5avZq1ym0x8328SyW0/qcIwlV9XJlkjtA573XYdS7PwAkQHGzJvCBoHE4KVuaaB/f0ej7J2JTAd+qvr3mNicuhu/M3QKRXx4VHXVwJN3mNA01ILIjR3sXeak7dWFxDWHE01kwa4yvTo2bcBgAL13SQxjHh5uBgMT0k+fe6eBlEYsABCAzYcMBtTytlcEz9679Db5umWb4dgAVEeqM/5AaeSNjXntumCkiWA6yNOPdbglFmrwacttFTeeT0144QyVGu8w06mzK3shkjuTgFwEgVs64ll3y3pWc5DZVEyjfkuAMoRoyotvQ4v73YWMEkyYLvw6/owO1qcYk2fW427g46/IwdXeA/8USvnz/QB/GDcKoe5/dfsApKYLGzbNCBNmrS+YVCOxfcC5RXVQcjekT8H1Nf/N+z4jl0RkfnL/wfBLpA5JNS5V/2aeT5gDijtzj9EyLDwYOEO2evPk+TChAtaT/zth+V+SRP+HuWXvgwi9P1M55J5zUAqKz9NvqxlPz86rBkb07mj+auwGyOFk6HFyiGez2UzYvdwpSEk="
    - secure: "VDvMItgWJptUvvE0hsN1vYIDgayu9x79Hsf7AK91ePHC0RjG9UfQwJF6mvKCqaLz17FTkVs6XSCFo+cqKkxsM5GdDd0ht5Y6nH7xhaUqKGsiLP8BMbR00ARjqWQqR1ea3njNWLqJXE5eIQ8sAITqg2GkFTDL+eXjgCy5R4DT2bFWo3drlulgjOKOr+qlPveUngx9pKHYNLvfE28Wj76htViaZTPQC23aVADL3B07nEYc4GAgKWl6u/YReceCO29BkNYeeaxMCatbyXwa2OuQmN8gfbjqSR/kEPnpA3jEPgc7ud2+Tkbke1M3bXQCI4NlC6u/uYK82ZZQSzJMhVS4BrEA1LfsEX285BBgCecpLQ4HX3iM0vAiQxImEEXpr+lmYIbYdFDw6GXit2BZh6V1gZ6yyv2bM/KpKkvlP1kwLNDkDml2m9xueEQz5vnyljgTafSZVeCvn4/b4E2vz3LS1WG8EUZaGXgC8GTPO6UTqQjmgvx6EsFZ+1oaL/b35uCPz999SzL/x/+B5JpZfc55SCe0ETceNK6ir1w0l+4tH3qNDyHeuPwUzuQUK8PMrm/uWfSgk19cMYfUy3A5x7mtN6y+WdeSiUwJSPGxeKWIp74GWYSU41tnZ2YzIf6n/sk9dAw1B+oXKizk/nMwDagiwwjqIrO7Fkj0Px6FYiZWtWs="

branches:
  except:
    - gh-pages

notifications:
  email: false
